# Generated by Django 5.1.3 on 2024-11-16 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='link',
            field=models.CharField(default=1, max_length=140),
            preserve_default=False,
        ),
    ]
